inspector:
    ingestion_key: '%env(INSPECTOR_INGESTION_KEY)%'
    transport: 'sync'
    ignore_routes:
        - '/_wdt*'
        - '/_profiler*'
    ignore_commands:
        - 'messenger*'
        - 'assets*'
        - 'importmap*'
        - 'cache*'
        - 'doctrine*'
        - 'schedule:run'
        - 'debug*'
        - 'make*'
